language: cpp

os:
  - linux
dist: trusty

sudo: required

compiler:
  - g++

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=$TRAVIS_BUILD_DIR/firmware/src

before_install:
  - git clone --depth=1 https://github.com/nnarain/travis-ci-scripts.git ~/scripts
  - cd ~/scripts/ && ./bootstrap && cd -
  - preinstall_general
  - pip install -U platformio

install:
  - install_general
  - install_boost 1.60.0 linux --with-system --with-filesystem --with-program_options
  - source /opt/boost_1_60_0/setup.bash

script:
  - ls $TRAVIS_BUILD_DIR
  - echo "Building pclights"
  - mkdir build && cd build
  - cmake ..
  - make
  - echo "Building pclights-firmware"
  - cd ../firmware
  - platformio ci --project-conf=platformio.ini --lib="./lib/SerialStream"

deploy:
  provider: releases
  api_key:
    secure: "n2hEalbehB9HWgd0ejPddkv/nrTPNK9+VriJDtpEw5cvm8ItRk7lSVFIFoJnM4GZQsEg/OcVku9MxUgJ16v9HCel78mkMCdqCVhmWj4NaVDr8qTUckoyCMe/7NXxx8KPI2tA5vj59D8oGx896zwNV52gLzreS5ByQJ5pSH8Y3DTaHxvq3vAxKMsrGY0s0nDutL698NRZo/n79AdcwMstBDOj7cuhe7HgwgzIbztTdZTSptcNBKHdqF6PY/tM87BWXcNk4RbLfKzZ/PXhZtKOk4ge95eyZbX4UqrcShEJcrQcONloiIymoHKULxT08VH/HNt6r2L5SkG3vEtPiS2H/Pq4L8E5httc7n6vrCbV9S8tyKe00oGZz0+GDOMjd7NgyFjhZ5j1wPqbyy2MvZTSm6gUU2uOc85bzDK8PnuSUJKo9bMEdSFIPajr49k5xqM7FqOyEvotNXmYNrKPUdjQxNKO8Yvc0v4mXudAsEPv1tQXjsyTozpHnjyIq7V+EX1EYECbYNoOWffHonITP9aSIAv192JkDW2qiPISmDGPAmE6ty/sKufjxKDeQo3yNxpopjWPr1jyucT0hoAP5y6q2Wow2+fhKxXhrMKqcvlPH9CxeB5w7uELCkTqT9ZWjjIIfbr6qTlNJDFq91DM1TOPaFEzn5XuCuB8Fbvqf0Yxk8E="
  file: ''
  skip_cleanup: true
  on:
    tags: true
